# Generated by Django 5.2.6 on 2025-09-09 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['step_number']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='officehour',
            name='day_label',
        ),
        migrations.RemoveField(
            model_name='page',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='og_image',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officehour',
            name='day',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords',
            field=models.TextField(blank=True, default='engineering, consultancy, infrastructure'),
        ),
        migrations.AddField(
            model_name='seo',
            name='page_title',
            field=models.CharField(default='Saizgar Engineering', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprocessstep',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='group',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='href',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_href',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='href',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='quickstat',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quickstat',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(default='Professional engineering consultancy services'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='Islamabad, Pakistan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@saizgar.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+92-51-1234567', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Saizgar Engineering', max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whychooseitem',
            name='description',
            field=models.TextField(),
        ),
    ]
