# Generated by Django 5.2.6 on 2025-09-09 18:59

from django.db import migrations


def fix_activities_data(apps, schema_editor):
    ServiceProcessStep = apps.get_model('cms', 'ServiceProcessStep')
    for step in ServiceProcessStep.objects.all():
        if step.activities and isinstance(step.activities, str):
            # Convert comma-separated string to list
            activities_list = [a.strip() for a in step.activities.split(',') if a.strip()]
            step.activities = activities_list
            step.save()


def reverse_fix_activities_data(apps, schema_editor):
    ServiceProcessStep = apps.get_model('cms', 'ServiceProcessStep')
    for step in ServiceProcessStep.objects.all():
        if step.activities and isinstance(step.activities, list):
            # Convert list back to comma-separated string
            step.activities = ', '.join(step.activities)
            step.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_corevalue_leadership_timelineevent_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_activities_data, reverse_fix_activities_data),
    ]
