# Generated by Django 5.2.6 on 2025-09-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150)),
                ('author_title', models.CharField(blank=True, max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('project_name', models.CharField(blank=True, help_text='Which project was this feedback for?', max_length=200)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
            ],
            options={
                'verbose_name': 'Client Feedback Submission',
                'verbose_name_plural': 'Client Feedback Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='submitted_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
