# Generated by Django 5.2.6 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='sector',
            name='icon',
        ),
        migrations.AddField(
            model_name='sector',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sector',
            name='capacity_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='capacity_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sectors/'),
        ),
        migrations.AddField(
            model_name='sector',
            name='coverage_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='coverage_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='key_projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sector',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sector',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='projects_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
